from OpenGL import GLUT

KEY_W = GLUT.as_8_bit("w")
KEY_S = GLUT.as_8_bit("s")
KEY_A = GLUT.as_8_bit("a")
KEY_D = GLUT.as_8_bit("d")
KEY_Q = GLUT.as_8_bit("q")
KEY_E = GLUT.as_8_bit("e")
KEY_O = GLUT.as_8_bit("o")
KEY_P = GLUT.as_8_bit("p")
KEY_K = GLUT.as_8_bit("k")
KEY_L = GLUT.as_8_bit("l")
KEY_N = GLUT.as_8_bit("n")
KEY_M = GLUT.as_8_bit("m")
KEY_B = GLUT.as_8_bit("b")
KEY_V = GLUT.as_8_bit("v")
KEY_Z = GLUT.as_8_bit("z")
KEY_H = GLUT.as_8_bit("h")
KEY_T = GLUT.as_8_bit("t")
KEY_Y = GLUT.as_8_bit("y")
KEY_G = GLUT.as_8_bit("g")
KEY_X = GLUT.as_8_bit("x")
KEY_C = GLUT.as_8_bit("c")